### ISSUE TITLE
I get this error only on red hat but it works great on other OS. Could you please help ?

### ISSUE THREAD

**Issue by jpca999** [ben-eb/gulp-csso#8] opened 2015-04-14 19:32 UTC
/home/username/workaccountclient/scripts/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line #1483
    at throwError (/home/msilberman/hmsaccountclient/scripts/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399:15)

**Comment by ben-eb** [comment] 2015-04-14 19:45
Looks like a duplicate of https://github.com/css/csso/issues/206 - will either be caused by malformed CSS or using a new (CSS4) property that csso does not understand.

**Comment by jpca999** [comment] 2015-04-14 19:47
I understnad if we add new css property that csso doesnt understnad but it works fine on all the OS except redhat.

**Comment by ben-eb** [comment] 2015-04-14 20:00
I'm not familiar with redhat I'm afraid. The other thing you might like to try is checking that you don't have any hidden characters in the CSS that are causing the parser to throw, such as a byte order mark.

https://github.com/css/csso/pull/223

**Comment by ben-eb** [comment] 2015-07-15 23:00
Closing as stale.

**Closed by ben-eb** 2015-07-15 23:00 UTC
Labels: duplicate
